### PR TITLE
updating to C++14

### PR DESCRIPTION
**Pull request by bgoodri**
This PR allows your package to build with rstan 2.18.1 on CRAN, which requires C++14. I have run R CMD check on your package from a Debian system similar to that on CRAN and uploaded the tarball to https://win-builder.r-project.org/ so the package maintainer should soon see the result of running R CMD check on Windows. If you have questions or issues, please post at https://discourse.mc-stan.org/t/how-to-update-a-package-that-has-stanheaders-and-rstan-in-its-linkingto/6041?u=bgoodri rather than, or in addition to, this PR so that other maintainers of R packages that use Stan can benefit from your experience. If all goes well with the R CMD check, please upload a new version to CRAN soon before your package gets kicked out.

### CODE REVIEW

**Review by saudiwin — APPROVED** [review]
These changes are also implemented in the version that will be released this week.

**Comment by bgoodri** [comment]
This got merged and then the C++14 thing subsequently got taken out. This is blocking the release of the next StanHeaders because running `R CMD check` on idealstan yields an error

> /opt/r-devel/library/StanHeaders/include/stan/math/rev/mat/functor/adj_jac_apply.hpp:31:54: note: deduced return type only available with -std=c++14 or -std=gnu++14
/opt/r-devel/library/StanHeaders/include/stan/math/rev/mat/functor/adj_jac_apply.hpp:48:48: error: ‘apply’ function uses ‘auto’ type specifier without trailing return type
 constexpr auto apply(const F& f, const Tuple& t) {

**Comment by saudiwin** [comment]
ok so I need to remove the C++ 14 thing?

**Comment by bgoodri** [comment]
No, idealstan needs to put it in

**Comment by saudiwin** [comment]
The current version on CRAN doesn't have this code?

**Comment by bgoodri** [comment]
It has C++11

https://github.com/saudiwin/idealstan/blob/master/src/Makevars#L3

**Comment by saudiwin** [comment]
Gotcha I changed it after it was merged in. It's just that C++14 thing right? That's the only change that is needed?

**Comment by saudiwin** [comment]
And only makevars.win too

**Comment by bgoodri** [comment]
Those are the only things that I know of, but rstanarm and the other
Stan-related packages that use C++14 didn't need any changes.

**Comment by saudiwin** [comment]
Ok so you're currently blocked from submitting Stanheaders until idealstan is updated? I can patch this now but I'd rather wait to release it with other new stuff coming later this month.

**Comment by bgoodri** [comment]
There is one other package with the same issue that is also blocking the StanHeaders release. Technically, I am supposed to be giving packages at least two weeks to fix things before releasing a StanHeaders that would be backwards incompatible. That hasn't elapsed, but I wanted to get all of the packages using C++14 back in October for exactly this reason. And I thought **idealstan** had done so, but then it got undone somewhere along the way. All of those messages on Discourse and GitHub about people not being able to get RStan to work with R 3.6  for Windows are due to us not being able to upload new versions.

**Comment by saudiwin** [comment]
OK I'm going to try pushing a patch. My memory is that I had some Windows compilation errors under the old Rstan with C++14 defined. If I can compile everything fine I'll push it out this week.

**Comment by saudiwin** [comment]
Hi Ben I'm still getting compile errors with switching to the CXX14 standard on windows. In particular, the `mingw_64` compiler fails with:

```
C:/Rtools/mingw_64/x86_64-w64-mingw32/include/c++/bits/c++0x_warning.h:32:2: 

error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
```

**Comment by bgoodri** [comment]
Do you have this [stuff](https://github.com/stan-dev/rstan/wiki/Installing-RStan-from-source-on-Windows#configuration) in your local ~/.R/Makevars or ~/.R/Makevars.win file?

**Comment by saudiwin** [comment]
OK I changed my Makevars.win and it was able to compile. But can I add those changes to Makevars.win to the build script somehow? I will need this to pass on Winbuilder if it's to get into CRAN.

**Comment by bgoodri** [comment]
winbuilder already has that

**Comment by saudiwin** [comment]
Ok great. I will run package checks and see if I can get a build to CRAN
this week.

**Comment by saudiwin** [comment]
Hi @bgoodri - just an FYI I had to remove -march=native from the Makevars.win to get the stan model to run. It would compile fine, but crash once it started sampling. Unless there is a reason it needs to be in there I intend to leave it out on submission to CRAN.

**Comment by bgoodri** [comment]
CRAN wouldn't let you put -march=native anyway, except maybe on Windows,
but even in that case you shouldn't because the compilation will be
specific to CRAN's servers.
